### ISSUE TITLE
Review of River Detail Main Tab

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/wh2o-vue#11]
River Detail Main Tab
- [ ] There is no pan/zoom option for the banner photo. We should either create a pan/zoom option or move to standard square/rectangular photo layout.
- [x] "Edit Beta Box" function is still a placeholder - needs completed. 
- [ ] I am curious if we can autofill the gradient field with GIS calculations (maybe a future project)
- [ ] Seems like "River Description edit menu function needs some way of clearing funky formatting (copy and paste errors, text size/font, etc), and perhaps dealing with legacy HTML.  
- [x] New alerts do not need the gage and flow fields - those are confusing. 
- [x] News thumbnail photos are not appearing.
- [x] "Add Rapid" button does nothing. 
- [ ] "Edit Rapid" option needs a mapping option rather than a manual "distance from put in" option. Ideally the distance will be calculated after the location is selected/edited and autogenerated. Like gradient, ideally our system can do this math for people. 
- [x] Under "Edit Rapid" and "Add Rapid" we need to add a couple fields to the "Characteristics" dropdown menu. Most importantly there is no "Rapid" option. "Play Spot" is another good option to add, and maybe an "Other" for folks to use for campsites and random other places.  

- [x] Adding a comment adds it 7 times. See https://wh2o-vue.herokuapp.com/#/river-detail/3341/main

- [x] Alerts appear twice. See https://wh2o-vue.herokuapp.com/#/river-detail/3341/main

**Comment by ngottlieb** [comment]
@AWKevin just a quick thought on gradient -- average gradient from put-in and take-out and length of the segment would be pretty straightforward, but I wonder if that actually misses some of the character that descriptors are trying to give? 

i.e. on a river that has a one mile long class I paddle in, then 1.5 miles of 300fpm...currently, are people writing 350fpm, or are they legitimately averaging the say total 500' over 2.5 miles and calling it 200fpm?

**Comment by AWKevin** [comment]
@ngottlieb legit question. My guess is that across the site gradient is either missing or inaccurate for a large majority of rivers. I have heard from one person freaking out that his gradient calculations would be better than a computer. I have a hard time believing that. I think average gradient is just that - objectively average rather than that of a user selected sub-reach. What I personally do for my adventures and find most useful is to have the gradient of each mile. That is better than "steepest mile" IMO. We could put this out to the stream team forum to see what folks think. I strongly favor a consistent accurate approach that populates all rivers objectively.

**Comment by drewalth** [comment]
1 - Perhaps it’s because I’ve been staring at this layout for three years, but this photo banner feels really stale / dated to me. I think we can come up with a better header layout one that really leans into the map, as that is the best part of this whole thing.

2 - Beta Box fields replicates those on beta: class, length, average gradient, and maximum gradient. 

3 - @ngottlieb ?

4 - Can you share a screenshot or elaborate on this more? The content editor allows you to do just that. I’ve also put into place a filter which removes inline styling and classes which will clean up all the old legacy html. I can make the filter more strict if needed.

5 - Removed.

6 - Fixed.

7 - @ngottlieb , I’ve added the NWI map component to the form but not sure how to handle the rest.

8 - I’ve added ‘Rapid’ and ‘Other’ as options to the dropdown. I do no know if we have an option for either, however. I think the system assumes it’s a rapid. @ryangroth5  should know.

**Comment by ngottlieb** [comment]
re: 7 -- I need to look at the code Seth wrote for selecting put-in and takeout. Presumably we can leverage this for rapid logging. My vote would be for this to be a post-deadline feature...but in theory the code is *mostly* there, we just need to leverage it for this purpose, so I'm not sure.

**Comment by AWKevin** [comment]
Re 1. I am stoked about this. Lets get a design that keeps the text from obscuring the photo on mobile, and as you know I've always been a fan of square or rectangular images so more photos look good/great. 

Re 2. The beta box looks nice, but my comment is that a user cannot edit its content. There is an edit option, but it is not complete or useable. 

Re 4. A lot of pages have legacy HTML in their layouts. Check this one as an example: https://wh2o-vue.herokuapp.com/#/river-detail/3341/main. Also, when creating articles we often end up with weird fonts and spacing and its nice to have a Tx button to clear the formatting. Not sure if this is a top priority, but if there is such an option in the plug in, turning it on would be good. 

Re 8. @ryangroth5 do we need a corresponding database change? It is really confusing to add a rapid and have no way of saying it is a rapid among all the choices. @drewalth "Add Rapid" button no longer does anything.

**Comment by ryangroth5** [comment]
(8) - rapid location? The database has a field to use in any way we wish for length from putin and location. Right now you specify both. In theory you can specify one and calculate the other. The purpose is that the AW site was supposed to originally replace a guidebook. 

In a guidebook you will see a table that says
```
Rapid     Mi 
Corkscrew 1.5 mi
Crack-In-the-Rock 3.0 mi 
Jawbone 3.1 mi 
Sock’em Dog 3.2 mi
```

Rapids was renamed to Points of Interest internally (POI) because it was already essentially used for that -- e.g. you could tag a non-rapid as a parking spot or a good place to take a photo. 

If you calculate mileage you might run into a problem with a feature that isn't on the river (for example a parking area that is marked, or an off-river hike). Since rapids are by definition on a river you would want to calculate mileage only on POIs with a rapid attribute.

Also calculating mileage may vary considerably depending on the resolution of the NHD. This is kinda like when I turn on strava and you turn on strava then we compare our results at the end of the same run and you ran 1 mi more than me and I climbed 300 ft higher than you even though we were on the same path. @ngottlieb  can speak more to that point.

You can also calculate location based on mileage along a river. Same caveats. 

The DB doesn't care though. It just happily stores the two pieces of data (lat/lon:POINT) and mileage:NUMBER.

**Comment by ryangroth5** [comment]
This evolved (not my decision) from the rapid list that I talk about to Kevin into kind of a chronical of things to expect on the river. Like 

1. arrive at **putin**, here is a  picture, look at the gauge
2. go down river and expect to see this **portage**
3. here is the first rapid
4. here is the next rapid
5. **play** here and eat lunch
6. if you break your neck here is the first place you can get to a road (e.g. **access**)
7. here is the class VI **waterfall & portage** portage right
8. **take out** on the right.

@drew the valid attributes are located in reach.gql any point can be any combination of these:
```
enum POIAttributes
{
	putin @enum(value:"putin"),
	takeout @enum(value:"takeout"),,
	access @enum(value:"access"),,
	portage @enum(value:"portage"),,
	hazard @enum(value:"hazard"),,
	waterfall @enum(value:"waterfall"),
	playspot  @enum(value:"playspot"),
}
```

I haven't added any, the system uses these to draw cute little icons next to the "rapids" even though a rapid probably isn't a rapid if it is marked as a "access". From a UI standpoint maybe lack of any attribute is a rapid and definition of an attribute that logically conflicts with a rapid is not a rapid (e.g. putin).

**Comment by AWKevin** [comment]
- [ ] Adding photo to a rapid description should be through picking a database photo, not via upload.
